name: Test

on:
  push:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build
      - name: Upload coverage
        uses: codecov/codecov-action@v1.5.2
        with:
          file: "!**/.nuget/packages/**/*.*"